import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

export enum PuestoEnum{
    MAESTRADELINEA="MAESTRADELINEA",
    TECNICODECALIDAD="TECNICODECALIDAD",
    AUXILIARDEMANTENIMIENTO="AUXILIARDEMANTENIMIENTO",
    OPDEPRODUCCION="OPDEPRODUCCION",
    AUDITOROBA="AUDITOROBA",
    SUPERVISOR="SUPERVISOR",
    ALMACENISTA="ALMACENISTA",
    AUXILIARDEINTENDENCIA="AUXILIARDEINTENDENCIA",
    TI="TI",
    JEFEDEMANTENIMIENTO="JEFEDEMANTENIMIENTO",
    INGENIERIADECALIDAD="INGENIERIADECALIDAD",
    INGENIERODEPROCESO="INGENIERODEPROCESO",
    GERENTEDECALIDAD="GERENTEDECALIDAD",
    INGENIERODENUEVOSPRODUCTOS="INGENIERODENUEVOSPRODUCTOS",
    TRAFICO="TRAFICO",
    GENERALISTADERH="GENERALISTADERH",
    JEFEDERECURSOSHUMANOS="JEFEDERECURSOSHUMANOS",
    INGENIERODECOTIZACIONES="INGENIERODECOTIZACIONES",
    RECLUTADOR="RECLUTADOR",
    AUXILIARDETRAFICO="AUXILIARDETRAFICO",
    AUXILIARDESOPORTETECNICO="AUXILIARDESOPORTETECNICO"
}

export enum PruebaEnum{
    PRUEBA="PRUEBA"
}

@Entity()
export class Puesto {
    @PrimaryGeneratedColumn()
    id:number
    @Column()
    puesto:string
}
